<LoginScreen>:
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            Label:
                text: 'Welcome to PyORAM'
        BoxLayout:
            size_hint_y: None
            height: 50
            Label:
                text: 'Enter Password:'
            TextInput:
                id: password
                password: True
                multiline: False
            Button:
                text: 'Start PyORAM'
                on_press: root.verify(password.text)